apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchworth-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchworth-backend
  template:
    metadata:
      labels:
        app: watchworth-backend
    spec:
      containers:
        - name: watchworth-backend
          image: cvsudeep/watchworthbackend:latest
#          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: watchworth-backend-config
                  key: DATASOURCE_URL
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: watchworth-backend-config
                  key: DATASOURCE_USERNAME
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: watchworth-backend-secret
                  key: DATASOURCE_PASSWORD
