apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchworth-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchworth-backend
  template:
    metadata:
      labels:
        app: watchworth-backend
    spec:
      containers:
        - name: watchworth-backend
          image: cvsudeep/watchworthbackend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: watchworth-backend-config
                  key: DATASOURCE_URL  # Reference the ConfigMap for DB URL
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: watchworth-backend-config
                  key: POSTGRES_USER  # Reference the ConfigMap for DB username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: watchworth-backend-secret
                  key: POSTGRES_PASSWORD  # Reference the Secret for DB password
