apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchworth-backend
spec:
  replicas: 2  # Ensures at least one pod is running
  selector:
    matchLabels:
      app: watchworth-backend
  template:
    metadata:
      labels:
        app: watchworth-backend
    spec:
      containers:
        - name: watchworth-backend
          image: cvsudeep/watchworthbackend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/ps_db
            - name: DATASOURCE_USERNAME
              value: root
            - name: DATASOURCE_PASSWORD
              value: root
          readinessProbe:  
            httpGet:
              path: /  
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:  
            httpGet:
              path: /  
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
