name: Deploy to OpenShift Sandbox

on:
  push:
    branches:
      - main  # Deploy when there's a push to the main branch

  schedule:
    - cron: "0 */10 * * *"  # Deploy every 10 hr

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install OpenShift CLI
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
        tar -xvzf oc.tar.gz
        sudo mv oc /usr/local/bin/

    - name: Log in to OpenShift
      env:
        OPENSHIFT_API_TOKEN: ${{ secrets.OPENSHIFT_API_TOKEN }}  # Your OpenShift API Token stored in repository secrets
      run: |
        oc login --token=$OPENSHIFT_API_TOKEN --server=https://api.sandbox-m3.1530.p1.openshiftapps.com:6443

    - name: Set OpenShift Project
      run: |
        oc project sudeepcv007-dev  # Replace this with your actual OpenShift project namespace

    - name: Build Docker Image for Multiple Architectures
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/watchworthbackend:latest . --push
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  # Your Docker Hub username
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}  # Your Docker Hub access token stored in repository secrets

    - name: Log in to Docker Hub
      run: |
        echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

    - name: Deploy to OpenShift
      run: |
        oc apply -f k8s-openshift/backend-deployment.yaml  # Apply the deployment manifest
        oc apply -f k8s-openshift/backend-service.yaml     # Apply the service manifest
        oc apply -f k8s-openshift/Route.yaml               # Apply the route for external access

    - name: Verify Deployment Rollout
      run: |
        oc rollout status deployment/watchworthbackend
